#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Process',     url: 'blog'}
- {name: 'Data',    url: 'about'}
- {name: 'Members',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '행정 구역',   url: 'proj-1'}
- {name: '인구',   url: 'proj-2'}
- {name: '경제 지표', url: 'proj-4'}
- {name: '철도 접근성', url: 'proj-3'}

#-------------------------------
# Contact Section

social:
#- {icon: 'instagram', link: 'https://www.instagram.com/jinuew/'}
#- {icon: 'github',    link: 'https://github.com/jinuew'}
#- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/%EC%A7%84%EC%9A%B0-%EB%B0%95-2240b3292/'}
#- {icon: 'envelope',  link: 'mailto:mailto:p_jinwoo98@naver.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
